# Generated by Django 3.1.3 on 2020-12-09 20:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='new_f',
            field=models.ManyToManyField(blank=True, related_name='msg', to=settings.AUTH_USER_MODEL),
        ),
    ]
