# Generated by Django 3.1.3 on 2020-12-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20201206_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='share_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
